version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      codeql-action:
        patterns: ["github/codeql-action/*"]
  - package-ecosystem: docker
    directory: /integration
    schedule:
      interval: weekly
